# Generated by Django 3.2.8 on 2021-10-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('minPrice', models.IntegerField()),
                ('maxPrice', models.IntegerField()),
                ('minYear', models.IntegerField()),
                ('maxYear', models.IntegerField()),
                ('minOdometer', models.IntegerField()),
                ('maxOdometer', models.IntegerField()),
                ('condition', models.IntegerField()),
                ('miles', models.IntegerField()),
                ('postalCode', models.IntegerField()),
                ('carModel', models.CharField(max_length=100)),
            ],
        ),
    ]
