# Generated by Django 3.2.8 on 2021-11-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='carModel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='condition',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='maxOdometer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='maxPrice',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='maxYear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='miles',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='minOdometer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='minPrice',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='minYear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='postalCode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='userId',
            field=models.IntegerField(null=True),
        ),
    ]
