# Generated by Django 3.2.8 on 2021-11-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0003_alter_parameters_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
