# Generated by Django 3.2.8 on 2021-11-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.IntegerField(null=True)),
                ('title', models.CharField(default='', max_length=200)),
                ('price', models.IntegerField(default=0, max_length=200)),
                ('posted', models.DateTimeField()),
            ],
        ),
    ]
