# Generated by Django 3.2.8 on 2021-11-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='posted',
            field=models.DateTimeField(null=True),
        ),
    ]
