# Generated by Django 3.2.8 on 2021-11-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_alter_auto_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='price',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
