# Generated by Django 3.2.8 on 2021-11-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_alter_auto_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
