# Generated by Django 3.2.8 on 2021-11-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_alter_auto_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='userId',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
